permissions:
  place-format: sff.place.%entity%
  break-format: sff.break.%entity%
  natural-drop: sff.natural

natural:
  silk-touch:
    enabled: true
    level: 1
    chance: 0.35
    require-permission: false

messages:
  break: "&cYou are not permitted to break %entity% spawner."
  place: "&cYou are not permitted to place %entity% spawner."
  natural-drop: "&aYou received a %entity% spawner!."
